# Generated by Django 5.2.5 on 2025-09-02 22:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='contenido',
            field=ckeditor.fields.RichTextField(verbose_name='contenido'),
        ),
    ]
