# Generated by Django 5.2.5 on 2025-09-05 19:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0002_pagina_orden_alter_pagina_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='contenido'),
        ),
    ]
