# Generated by Django 5.2.5 on 2025-09-16 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0003_alter_pagina_contenido'),
        ('blog', '0008_remove_tipo_subcategoria_tipo_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paginas', to='blog.tipo', verbose_name='Tipo de Artículo'),
        ),
    ]
