# Generated by Django 5.2.5 on 2025-09-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0004_pagina_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagina',
            options={'ordering': ['orden', '-creacion'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.AddField(
            model_name='pagina',
            name='es_inicio',
            field=models.BooleanField(default=False, verbose_name='Página de inicio'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True, verbose_name='URL_SLUG'),
        ),
    ]
