# Generated by Django 5.2.5 on 2025-10-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0005_alter_pagina_options_pagina_es_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='solo_layout',
            field=models.BooleanField(default=False, verbose_name='Vista solo en layout'),
        ),
    ]
