# Generated by Django 5.2.5 on 2025-10-07 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0006_pagina_solo_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='solo_layout',
        ),
    ]
