# Generated by Django 5.2.5 on 2025-10-17 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0007_remove_pagina_solo_layout'),
        ('blog', '0020_alter_articulo_usar_miniatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='es_inicio',
            field=models.BooleanField(default=False, help_text='Solo puede haber 1 página con esta opción. Al estar activa el slug pasa a estar vacío; y será la primera página en mostrarse', verbose_name='Página de inicio'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Indica que tipo de artículo se mostrara en las Categorías o Subcategorías de la página', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paginas', to='blog.tipo', verbose_name='Tipo de Artículo'),
        ),
    ]
