# Generated by Django 5.2.5 on 2025-10-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0008_alter_pagina_es_inicio_alter_pagina_tipo'),
        ('blog', '0021_remove_tipo_subcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='es_inicio',
            field=models.BooleanField(default=False, help_text='Solo puede haber una página con esta opción. Al estar activa, el slug pasa a estar vacío y será la primera página en mostrarse.', verbose_name='Página de inicio'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Indica qué tipo de artículo se mostrará en las categorías o subcategorías de la página.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paginas', to='blog.tipo', verbose_name='Tipo de Artículo'),
        ),
    ]
