# Generated by Django 5.2.5 on 2025-10-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0010_pagina_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='slug',
            field=models.SlugField(blank=True, help_text='Si se deja vacío, se generará automáticamente a partir del título.', max_length=150, unique=True, verbose_name='URL_SLUG'),
        ),
    ]
