# Generated by Django 5.2.5 on 2025-10-20 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0011_alter_pagina_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='orden',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Orden'),
        ),
    ]
