# Generated by Django 5.2.5 on 2026-01-05 21:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0012_alter_pagina_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
