# Generated by Django 5.2.5 on 2025-09-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL_SLUG')),
                ('publico', models.BooleanField(verbose_name='Publicado')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificacion', models.DateTimeField(auto_now=True, verbose_name='Ultima modificación')),
            ],
        ),
    ]
