# Generated by Django 5.2.5 on 2025-09-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagina',
        ),
    ]
