# Generated by Django 5.2.5 on 2025-09-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0002_delete_pagina'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Mi sitio', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
