# Generated by Django 5.2.5 on 2025-12-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_rol_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Layout',
        ),
    ]
