# Generated by Django 5.2.5 on 2025-09-02 23:21

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('desc', models.CharField(max_length=255, verbose_name='Descripción')),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('contenido', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Contenido')),
                ('imagen', models.ImageField(default='null', upload_to='articulos', verbose_name='Miniatura')),
                ('publico', models.BooleanField(verbose_name='Publicado')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='creación')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='ultima modificación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('categorias', models.ManyToManyField(blank=True, null=True, to='blog.categoria', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': ' artículo',
                'verbose_name_plural': ' artículos',
            },
        ),
    ]
