# Generated by Django 5.2.5 on 2025-09-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articulo_options_alter_articulo_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categorias',
            field=models.ManyToManyField(related_name='subcategorias', to='blog.categoria', verbose_name='Categorías'),
        ),
    ]
