# Generated by Django 5.2.5 on 2025-09-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0003_alter_pagina_contenido'),
        ('blog', '0003_remove_subcategoria_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='pag',
            field=models.ManyToManyField(blank=True, to='AppPagina.pagina', verbose_name='Paginas'),
        ),
    ]
