# Generated by Django 5.2.5 on 2025-09-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0003_alter_pagina_contenido'),
        ('blog', '0004_categoria_pag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='pag',
        ),
        migrations.AddField(
            model_name='categoria',
            name='paginas',
            field=models.ManyToManyField(blank=True, related_name='categorias', to='AppPagina.pagina', verbose_name='Páginas'),
        ),
    ]
