# Generated by Django 5.2.5 on 2025-09-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_categoria_pag_categoria_paginas'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='publico',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
    ]
