# Generated by Django 5.2.5 on 2025-09-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tipo_articulo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='tipo',
            name='subcategoria',
            field=models.ManyToManyField(related_name='Tipo', to='blog.subcategoria', verbose_name='subcategoria'),
        ),
    ]
