# Generated by Django 5.2.5 on 2025-09-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_tipo_subcategoria_tipo_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='subcategoria',
            field=models.ManyToManyField(blank=True, null=True, related_name='Tipo', to='blog.subcategoria', verbose_name='subcategoria'),
        ),
    ]
