# Generated by Django 5.2.5 on 2025-09-26 18:27

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_tipo_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
