# Generated by Django 5.2.5 on 2025-09-30 17:46

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_articulo_video_subcategoria_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='video',
        ),
        migrations.AddField(
            model_name='articulo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Video (URLS)'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(default='null', upload_to='articulos/', verbose_name='Miniatura'),
        ),
    ]
