# Generated by Django 5.2.5 on 2025-09-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_articulo_video_articulo_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Videos (ARCHIVO)'),
        ),
    ]
