# Generated by Django 5.2.5 on 2025-09-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_articulo_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
    ]
