# Generated by Django 5.2.5 on 2025-09-30 18:34

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_subcategoria_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='video',
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Videos (ARCHIVO)'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Video (URLS)'),
        ),
    ]
