# Generated by Django 5.2.5 on 2025-09-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_subcategoria_video_subcategoria_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='subcategoria',
            field=models.ManyToManyField(blank=True, related_name='tipos', to='blog.subcategoria', verbose_name='subcategoria'),
        ),
    ]
