# Generated by Django 5.2.5 on 2025-10-01 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_tipo_slug_alter_tipo_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='categorias',
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria', verbose_name='Categorias'),
        ),
    ]
