# Generated by Django 5.2.5 on 2025-10-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_articulo_categorias_articulo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='usar_miniatura',
            field=models.BooleanField(default=False, verbose_name='¿Usar miniatura en el artículo?'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null='True', upload_to='thumbnails/', verbose_name='Miniatura'),
        ),
    ]
