# Generated by Django 5.2.5 on 2025-10-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_articulo_usar_miniatura_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='usar_miniatura',
            field=models.BooleanField(default=False, verbose_name='¿Usar miniatura?'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='usar_miniatura',
            field=models.BooleanField(default=False, verbose_name='¿Usar miniatura?'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='imagen',
            field=models.ImageField(blank=True, null='True', upload_to='thumbnails/', verbose_name='Miniatura'),
        ),
    ]
