# Generated by Django 5.2.5 on 2025-10-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_subcategoria_usar_miniatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='usar_miniatura',
            field=models.BooleanField(default=False, help_text='Si marcás esto, el sistema intentará usar la miniatura del video (o generar/descargar una) como imagen.', verbose_name='¿Usar miniatura?'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='usar_miniatura',
            field=models.BooleanField(default=False, help_text='Si marcás esto, el sistema intentará usar la miniatura del video (o generar/descargar una) como imagen.', verbose_name='¿Usar miniatura?'),
        ),
    ]
