# Generated by Django 5.2.5 on 2025-10-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_articulo_usar_miniatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='usar_miniatura',
            field=models.BooleanField(default=False, help_text='Si marcás esto, indicaras si la miniatura que tienes cargada se vera o no; Si no hay miniatura cargada, el sistema intentará usar cargar la miniatura del video cuando guardes.', verbose_name='¿Usar miniatura?'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='usar_miniatura',
            field=models.BooleanField(default=False, help_text='Si marcás esto, indicaras si la miniatura que tienes cargada se vera o no; Si no hay miniatura cargada, el sistema intentará usar cargar la miniatura del video cuando guardes.', verbose_name='¿Usar miniatura?'),
        ),
    ]
