# Generated by Django 5.2.5 on 2025-10-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_articulo_usar_miniatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='subcategoria',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='usar_miniatura',
            field=models.BooleanField(default=False, help_text='Si marcás esto, indicarás si la miniatura que tenés cargada se verá o no. Si no hay una miniatura cargada, el sistema intentará obtenerla del vídeo después de guardar.', verbose_name='¿Usar miniatura?'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='usar_miniatura',
            field=models.BooleanField(default=False, help_text='Si marcás esto, indicarás si la miniatura que tenés cargada se verá o no. Si no hay una miniatura cargada, el sistema intentará obtenerla del vídeo después de guardar.', verbose_name='¿Usar miniatura?'),
        ),
    ]
