# Generated by Django 5.2.5 on 2025-10-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_categoria_usuario_subcategoria_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='slug',
            field=models.SlugField(blank=True, help_text='Si se deja vacío, se generará automáticamente a partir del nombre.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='slug',
            field=models.SlugField(blank=True, help_text='Si se deja vacío, se generará automáticamente a partir del nombre.', max_length=150, unique=True),
        ),
    ]
