# Generated by Django 5.2.5 on 2025-10-24 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_subcategoria_slug_alter_tipo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='categorias',
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='blog.categoria', verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
