# Generated by Django 5.2.5 on 2025-12-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_layout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layout',
            options={'verbose_name': 'Layout', 'verbose_name_plural': '00 - Layout'},
        ),
    ]
