# Generated by Django 5.2.5 on 2025-12-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_layout_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layout',
            options={},
        ),
    ]
