# Generated by Django 5.2.5 on 2026-01-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_articulo_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='publico',
        ),
    ]
